# Kodiak configuration for automated PR merging
# https://kodiakhq.com/docs/config-reference

version = 1

[merge]
# Merge automatically when all required checks pass
automerge_label = "automerge"
blacklist_title_regex = "^WIP.*|^Draft.*"
blacklist_labels = ["work-in-progress", "do-not-merge", "hold"]
require_automerge_label = false

# Method to use for merging PRs
method = "squash"

# Delete branch after successful merge
delete_branch_on_merge = true

# Automatically add automerge label to dependency PRs
optimistic_updates = false

# Don't merge if failing checks
strict_method = "squash"

[merge.message]
# Use PR title and body for commit message
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true

[approve]
# Auto-approve dependency PRs from renovate
auto_approve_usernames = ["renovate[bot]"]
auto_approve_labels = ["dependencies"]

[merge.automerge_dependencies]
# Auto-merge specific types of dependency updates
usernames = ["renovate[bot]", "dependabot[bot]"]
versions = ["patch", "minor"]

[update]
# Keep PRs up to date with target branch
always = true
require_automerge_label = false

[merge.do_not_merge]
# Don't merge if these labels are present
labels = [
    "work-in-progress",
    "do-not-merge", 
    "hold",
    "needs-review",
    "breaking-change"
]

# Don't merge if title contains these patterns
title_regex = "^(WIP|Draft|DRAFT):.*"

[merge.block_on_reviews_requested]
# Don't merge if reviews are explicitly requested
enabled = true

[merge.prioritize_ready_to_merge]
# Merge PRs that are ready to merge first
enabled = true
