name: Spell Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  spell-check:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spell Check with CSpell
        uses: streetsidesoftware/cspell-action@v5
        with:
          # Check these file types
          files: |
            **/*.{md,mdx,txt}
            src/**/*.{astro,ts,tsx,js,jsx}
            README.md
          # Don't fail the build, just report
          strict: false
          # Use inline reporting
          inline: warning
          # Custom configuration
          config: |
            {
              "version": "0.2",
              "language": "en",
              "words": [
                "astro",
                "astrojs",
                "brutalist",
                "Ioannis",
                "Lougiakis",
                "dacrab",
                "github",
                "typescript",
                "lightningcss",
                "jsx",
                "tsx",
                "eslint",
                "tsconfig"
              ],
              "ignoreWords": [
                "IOANNIS",
                "LOUGIAKIS"
              ],
              "ignorePaths": [
                "node_modules/**",
                "dist/**",
                ".astro/**",
                "*.lock",
                "*.lockb",
                "package-lock.json",
                "bun.lock"
              ]
            }
